name: Trigger auto deployment for container-app-7ns7aibkzp2ho

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-7ns7aibkzp2ho-AutoDeployTrigger-515bdee7-dfdc-4de1-8830-8e51f2a86dcf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP7NS7AIBKZP2HO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP7NS7AIBKZP2HO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP7NS7AIBKZP2HO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry7ns7aibkzp2ho.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP7NS7AIBKZP2HO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP7NS7AIBKZP2HO_REGISTRY_PASSWORD }}
          containerAppName: container-app-7ns7aibkzp2ho
          resourceGroup: ehexpress008901
          imageToBuild: containerregistry7ns7aibkzp2ho.azurecr.io/container-app-7ns7aibkzp2ho:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


